import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './config.js';
const $=id=>document.getElementById(id);
const configured=SUPABASE_URL.startsWith('https://')&&SUPABASE_PUBLISHABLE_KEY!=='PASTE_YOUR_SUPABASE_PUBLISHABLE_KEY';
let db=null, jobs=[], customers=[], items=[], notices=[];
const statuses=['New','Pretreatment','Powder Coating','Curing / QC','Ready for Collection','Collected'];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const msg=x=>{const t=$('toast');t.textContent=x;t.style.display='block';setTimeout(()=>t.style.display='none',5500)};
const check=(res)=>{if(res.error)throw res.error;return res.data};
function urgency(j){if(['Collected','Ready for Collection'].includes(j.status))return ['ok',j.status];const days=Math.ceil((new Date(j.due_date+'T23:59:59')-new Date())/86400000);return days<0?['overdue',`${Math.abs(days)} day(s) overdue`]:days<=2?['urgent',days===0?'Due today':`Due in ${days} day(s)`]:['ok',`Due in ${days} day(s)`]}
function show(tab){for(const el of ['dashboard','new','review','collected'])$(el).classList.toggle('hide',el!==tab);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab))}
function itemRow(){const d=document.createElement('div');d.className='item';d.innerHTML=`<div class="row"><div><label>Item</label><input class="desc" required placeholder="Steel brackets"></div><div><label>Quantity</label><input class="qty" type="number" min="1" value="1" required></div><div><label>Colour</label><input class="colour" placeholder="Matt black"></div><div><label>Dimensions</label><input class="dimensions" placeholder="L x W x H"></div><div><label>Price (R)</label><input class="price" type="number" min="0" step="0.01" value="0"></div><button type="button" class="secondary remove">Remove</button></div>`;d.querySelector('.remove').onclick=()=>{if($('items').children.length>1)d.remove()};$('items').appendChild(d)}
async function load(){jobs=check(await db.from('jobs').select('*').order('created_at',{ascending:false}));customers=check(await db.from('customers').select('*'));items=check(await db.from('job_items').select('*'));notices=check(await db.from('notifications').select('*'));render()}
function render(){const active=jobs.filter(j=>j.status!=='Collected');const late=active.filter(j=>urgency(j)[0]==='overdue');const urgent=active.filter(j=>urgency(j)[0]==='urgent');$('stats').innerHTML=[['Active jobs',active.length],['Urgent',urgent.length],['Overdue',late.length],['Ready for collection',active.filter(j=>j.status==='Ready for Collection').length]].map(([n,v])=>`<div class="panel"><div class="stat">${v}</div><div class="muted">${n}</div></div>`).join('');$('jobs').innerHTML=active.map(jobHTML).join('')||'<p class="muted">No active jobs yet.</p>';$('archive').innerHTML=jobs.filter(j=>j.status==='Collected').map(jobHTML).join('')||'<p>No collected jobs yet.</p>';$('reviews').innerHTML=notices.filter(n=>n.kind==='delay'&&n.status==='draft').map(n=>`<div class="job"><strong>${esc(jobs.find(j=>j.id===n.job_id)?.job_number||'Job')}</strong><p>${esc(n.message)}</p><button data-approve="${n.id}">Approve for future sending</button> <button class="secondary" data-dismiss="${n.id}">Dismiss</button></div>`).join('')||'<p class="muted">No delay messages awaiting review.</p>';}
function jobHTML(j){const c=customers.find(x=>x.id===j.customer_id)||{};const [cls,urg]=urgency(j);const list=items.filter(i=>i.job_id===j.id);const notification=notices.find(n=>n.job_id===j.id&&n.kind==='collection');return `<div class="job"><div class="job-head"><div><strong>${esc(j.job_number)}</strong> — ${esc(c.name)} <span class="chip ${cls}">${esc(urg)}</span><div class="muted">${esc(c.phone)} · Due ${esc(j.due_date)}</div></div><div><select data-status="${j.id}" aria-label="Change job status">${statuses.map(s=>`<option ${s===j.status?'selected':''}>${esc(s)}</option>`).join('')}</select></div></div><div class="muted">${list.map(i=>`${esc(i.quantity)} × ${esc(i.description)} (${esc(i.colour)})`).join(' · ')||'No items'}</div><div class="row"><div><label>Invoice PDF (max 10 MB)</label><input type="file" accept="application/pdf,.pdf" data-file="${j.id}"></div><div>${j.invoice_path?`<button class="secondary" data-invoice="${j.id}">View saved PDF</button>`:'<span class="muted">No invoice uploaded</span>'}</div></div>${notification?`<p class="muted">Collection WhatsApp: ${esc(notification.status.replaceAll('_',' '))}. ${notification.status==='pending_integration'?'Automatic sending is not connected yet.':''}</p>`:''}</div>`}
async function transition(id,status){const j=jobs.find(x=>x.id===id);if(!j||j.status===status)return;if(status==='Ready for Collection'&&!j.invoice_path){msg('Upload the invoice PDF before marking this job ready for collection.');render();return}try{check(await db.from('jobs').update({status,updated_at:new Date().toISOString()}).eq('id',id));check(await db.from('job_history').insert({job_id:id,status}));if(status==='Ready for Collection'){const c=customers.find(x=>x.id===j.customer_id);const text=`Good day ${c?.name||''}, your EnduraCoat job ${j.job_number} is ready for collection. Your invoice PDF is attached. Thank you!`;check(await db.from('notifications').upsert({job_id:id,kind:'collection',status:'pending_integration',message:text},{onConflict:'job_id,kind'}));msg('Job ready. WhatsApp queued as pending integration — NOT sent.')}else msg('Job updated');await load()}catch(e){msg('Could not update job: '+e.message);await load()}}
async function uploadInvoice(id,file){if(!file)return;if(file.type!=='application/pdf'||!file.name.toLowerCase().endsWith('.pdf')||file.size>10*1024*1024){msg('Choose a PDF file under 10 MB.');return}try{const path=`${id}/${crypto.randomUUID()}.pdf`;check(await db.storage.from('invoices').upload(path,file,{contentType:'application/pdf',upsert:false}));check(await db.from('jobs').update({invoice_path:path,invoice_name:file.name}).eq('id',id));msg('Invoice uploaded securely');await load()}catch(e){msg('Upload failed: '+e.message)}}
async function viewInvoice(id){const j=jobs.find(x=>x.id===id);if(!j?.invoice_path)return;try{const r=check(await db.storage.from('invoices').createSignedUrl(j.invoice_path,60));window.open(r.signedUrl,'_blank','noopener,noreferrer')}catch(e){msg(e.message)}}
async function makeDelayReviews(){for(const j of jobs){if(urgency(j)[0]!=='overdue'||['Collected','Ready for Collection'].includes(j.status)||notices.some(n=>n.job_id===j.id&&n.kind==='delay'))continue;const c=customers.find(x=>x.id===j.customer_id);const message=`Good day ${c?.name||''}, we apologise that your EnduraCoat job ${j.job_number} has been delayed. We will confirm an updated collection date shortly.`;check(await db.from('notifications').insert({job_id:j.id,kind:'delay',status:'draft',message}));}await load()}
async function boot(){if(!configured){$('setup').classList.remove('hide');return}db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);const {data:{session}}=await db.auth.getSession();await authView(session);db.auth.onAuthStateChange((_event,session)=>{setTimeout(()=>authView(session),0)})}
async function authView(session){$('login').classList.toggle('hide',!!session);$('app').classList.toggle('hide',!session);$('logout').classList.toggle('hide',!session);if(session){try{const staff=check(await db.from('staff').select('user_id').eq('user_id',session.user.id).maybeSingle());if(!staff){$('app').classList.add('hide');msg('Account not authorised. Add this user UUID to public.staff in Supabase.');return}await load();await makeDelayReviews()}catch(e){msg('Database error: '+e.message)}}}
$('loginForm').onsubmit=async e=>{e.preventDefault();const r=await db.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(r.error)msg(r.error.message)};
$('logout').onclick=()=>db.auth.signOut();document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>show(b.dataset.tab));$('refresh').onclick=()=>load().catch(e=>msg(e.message));$('addItem').onclick=itemRow;itemRow();
$('jobForm').onsubmit=async e=>{e.preventDefault();const b=$('saveJob');b.disabled=true;try{let c=customers.find(c=>c.name.toLowerCase()===$('customer').value.trim().toLowerCase()&&c.phone===$('phone').value.trim());if(!c)c=check(await db.from('customers').insert({name:$('customer').value.trim(),phone:$('phone').value.trim()}).select().single());const job=check(await db.from('jobs').insert({job_number:$('jobno').value.trim(),customer_id:c.id,due_date:$('due').value,notes:$('notes').value}).select().single());const rows=[...document.querySelectorAll('#items .item')].map(x=>({job_id:job.id,description:x.querySelector('.desc').value,quantity:Number(x.querySelector('.qty').value),colour:x.querySelector('.colour').value,dimensions:x.querySelector('.dimensions').value,price:Number(x.querySelector('.price').value)||0}));check(await db.from('job_items').insert(rows));check(await db.from('job_history').insert({job_id:job.id,status:'New'}));$('jobForm').reset();$('items').innerHTML='';itemRow();await load();show('dashboard');msg('Job saved to cloud')}catch(e){msg('Save failed: '+e.message)}finally{b.disabled=false}};
document.addEventListener('change',async e=>{const t=e.target;if(t.dataset.status)await transition(t.dataset.status,t.value);if(t.dataset.file)await uploadInvoice(t.dataset.file,t.files?.[0])});document.addEventListener('click',async e=>{const t=e.target;if(t.dataset.invoice)await viewInvoice(t.dataset.invoice);if(t.dataset.approve||t.dataset.dismiss){const id=t.dataset.approve||t.dataset.dismiss;try{check(await db.from('notifications').update({status:t.dataset.approve?'approved':'failed'}).eq('id',id));msg(t.dataset.approve?'Approved for future backend sending — NOT sent yet':'Dismissed');await load()}catch(err){msg(err.message)}}});
boot().catch(e=>msg(e.message));
