import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './config.js';
const $=id=>document.getElementById(id);
const configured=SUPABASE_URL.startsWith('https://')&&SUPABASE_PUBLISHABLE_KEY!=='PASTE_YOUR_SUPABASE_PUBLISHABLE_KEY';
let db=null, jobs=[], customers=[], items=[], notices=[], stagePlans=[];
let editRemoved=new Set();
let plannerWeekOffset=0;
const statuses=['New','Pretreatment','Powder Coating','Curing / QC','Ready for Collection','Collected'];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const msg=x=>{const t=$('toast');t.textContent=x;t.style.display='block';setTimeout(()=>t.style.display='none',5500)};
const check=(res)=>{if(res.error)throw res.error;return res.data};
function urgency(j){if(['Collected','Ready for Collection'].includes(j.status))return ['ok',j.status];const days=Math.ceil((new Date(j.due_date+'T23:59:59')-new Date())/86400000);return days<0?['overdue',`${Math.abs(days)} day(s) overdue`]:days<=2?['urgent',days===0?'Due today':`Due in ${days} day(s)`]:['ok',`Due in ${days} day(s)`]}
function show(tab){for(const el of ['dashboard','new','planner','review','collected'])$(el).classList.toggle('hide',el!==tab);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab))}
function itemRow(){const d=document.createElement('div');d.className='item';d.innerHTML=`<div class="row"><div><label>Item</label><input class="desc" required placeholder="Steel brackets"></div><div><label>Quantity</label><input class="qty" type="number" min="1" value="1" required></div><div><label>Colour</label><input class="colour" placeholder="Matt black"></div><div><label>Dimensions</label><input class="dimensions" placeholder="L x W x H"></div><div><label>Price (R)</label><input class="price" type="number" min="0" step="0.01" value="0"></div><button type="button" class="secondary remove">Remove</button></div>`;d.querySelector('.remove').onclick=()=>{if($('items').children.length>1)d.remove()};$('items').appendChild(d)}
async function load(){jobs=check(await db.from('jobs').select('*').order('created_at',{ascending:false}));customers=check(await db.from('customers').select('*'));items=check(await db.from('job_items').select('*'));notices=check(await db.from('notifications').select('*'));stagePlans=check(await db.from('job_stage_schedule').select('*'));render()}
function whatsappPhone(raw){let p=String(raw||'').replace(/\D/g,'');if(p.startsWith('00'))p=p.slice(2);if(p.startsWith('0'))p='27'+p.slice(1);if(p.length===9)p='27'+p;return /^\d{10,15}$/.test(p)?p:null}
function reviewHTML(n){const j=jobs.find(x=>x.id===n.job_id),c=customers.find(x=>x.id===j?.customer_id)||{},phone=whatsappPhone(c.phone);const kind=n.kind==='collection'?'Collection':'Delay';return `<div class="job"><div class="job-head"><strong>${esc(j?.job_number||'Job')} — ${kind}</strong><span class="chip">${esc(n.status==='sent'?'Sent':n.status==='approved'?'Approved / unsent':'Needs review')}</span></div><p class="muted">${esc(c.name||'Customer')} · ${esc(c.phone||'No phone')}</p><label>Message (copy or open WhatsApp to edit before sending)</label><textarea data-message="${n.id}" rows="4">${esc(n.message)}</textarea><div class="row review-actions"><button class="secondary" data-copy="${n.id}">Copy message</button><button data-whatsapp="${n.id}" ${phone?'':'disabled title="Add a valid WhatsApp number to the customer"'}>Open WhatsApp</button>${j?.invoice_path?`<button class="secondary" data-review-invoice="${j.id}">Open invoice PDF</button>`:'<span class="muted">No invoice attached</span>'}<button class="secondary" data-sent="${n.id}">Mark as Sent</button><button class="secondary" data-dismiss="${n.id}">Dismiss</button></div><p class="muted">${n.kind==='collection'?(j?.invoice_path?'Attach the invoice PDF manually in WhatsApp. ':'No invoice attached; you can upload one later. '):''}Opening WhatsApp does not send the message.</p></div>`}
function render(){
 const active=jobs.filter(j=>j.status!=='Collected');
 const late=active.filter(j=>urgency(j)[0]==='overdue');
 const urgent=active.filter(j=>urgency(j)[0]==='urgent');
 const pending=notices.filter(n=>['draft','approved','pending_integration'].includes(n.status));
 const badge=$('reviewBadge');
 if(badge){
   badge.textContent=String(pending.length);
   badge.classList.toggle('hide',pending.length===0);
   badge.setAttribute('aria-label',`${pending.length} messages awaiting review`);
   const reviewTab=document.querySelector('[data-tab="review"]');
   if(reviewTab)reviewTab.setAttribute('aria-label',pending.length?`Review, ${pending.length} messages awaiting review`:'Review, no pending messages');
 }
 const metrics=[['Active jobs',active.length,'◫',''],['Due soon',urgent.length,'◷',''],['Overdue',late.length,'!','metric-danger'],['Ready to collect',active.filter(j=>j.status==='Ready for Collection').length,'✓','metric-ready'],['Review messages',pending.length,'✉','metric-review']];
 $('stats').innerHTML=metrics.map(([name,count,icon,cls])=>`<div class="metric ${cls}"><span class="metric-icon" aria-hidden="true">${icon}</span><div class="metric-value">${count}</div><div class="metric-label">${name}</div></div>`).join('');
 $('dashboardDate').textContent=new Intl.DateTimeFormat('en-ZA',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());
 const stages=[['New','#94a3b8'],['Pretreatment','#60a5fa'],['Powder Coating','#f59e0b'],['Curing / QC','#a78bfa'],['Ready for Collection','#4ade80']];
 const max=Math.max(1,...stages.map(([s])=>active.filter(j=>j.status===s).length));
 $('pipeline').innerHTML=stages.map(([s,color])=>{const count=active.filter(j=>j.status===s).length;return `<div class="pipeline-row"><span class="pipeline-name">${esc(s)}</span><div class="pipeline-track"><div class="pipeline-fill" style="width:${100*count/max}%;background:${color}"></div></div><span class="pipeline-count">${count}</span></div>`}).join('');
 const needs=[...late,...urgent].sort((a,b)=>a.due_date.localeCompare(b.due_date)).slice(0,5);
 $('attention').innerHTML=needs.map(j=>`<div class="attention-row"><div class="attention-title">${esc(j.job_number)} · ${esc(customers.find(c=>c.id===j.customer_id)?.name||'Customer')}</div><div class="attention-sub">${esc(urgency(j)[1])} · ${esc(j.status)}</div></div>`).join('')||'<div class="empty">No urgent jobs right now.</div>';
 renderJobList();
 renderPlanner();
 renderStagePlanner();
 $('archive').innerHTML=jobs.filter(j=>j.status==='Collected').map(jobHTML).join('')||'<p class="muted">No collected jobs yet.</p>';
 $('reviews').innerHTML=pending.map(reviewHTML).join('')||'<p class="muted">No messages awaiting review.</p>';
 $('reviewHistory').innerHTML=notices.filter(n=>['sent','failed'].includes(n.status)).map(n=>`<div class="job"><strong>${esc(jobs.find(j=>j.id===n.job_id)?.job_number||'Job')}</strong> — ${esc(n.kind)} · ${n.status==='sent'?'Marked sent':'Dismissed'}<p class="muted">${esc(n.message)}</p></div>`).join('')||'<p class="muted">No reviewed messages yet.</p>';
}
function localISO(date){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`}
function weekStart(offset){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7)+offset*7);return d}
function planCard(j){
 const c=customers.find(c=>c.id===j.customer_id);
 const overdue=j.due_date<localISO(new Date())&&!['Ready for Collection','Collected'].includes(j.status);
 return `<article class="planner-job ${overdue?'planner-late':j.status==='Ready for Collection'?'planner-ready':''}" draggable="true" data-drag-job="${esc(j.id)}" tabindex="0" aria-label="${esc(j.job_number)}. Drag to a production day or use Schedule"><strong>${esc(j.job_number)}</strong><span>${esc(c?.name||'Customer')} · ${esc(j.status)}</span><span>Promised: ${esc(j.due_date)}${overdue?' · OVERDUE':''}</span><div class="plan-actions"><button class="secondary" data-schedule="${esc(j.id)}">Schedule</button><button class="secondary" data-edit="${esc(j.id)}">Edit</button></div></article>`;
}
function renderPlanner(){
 const start=weekStart(plannerWeekOffset),end=new Date(start);end.setDate(start.getDate()+6);
 const fmt=new Intl.DateTimeFormat('en-ZA',{day:'numeric',month:'short'});
 $('plannerRange').textContent=`${fmt.format(start)} – ${fmt.format(end)} ${end.getFullYear()}`;
 const today=localISO(new Date()),startISO=localISO(start),endISO=localISO(end);
 const active=jobs.filter(j=>j.status!=='Collected');
 const planned=active.filter(j=>j.planned_date>=startISO&&j.planned_date<=endISO);
 const backlog=active.filter(j=>!j.planned_date);
 const overdue=active.filter(j=>j.due_date<today&&j.status!=='Ready for Collection');
 $('plannerSummary').innerHTML=`<div class="planner-pill"><strong>${planned.length}</strong> Scheduled this week</div><div class="planner-pill"><strong>${backlog.length}</strong> Unscheduled</div><div class="planner-pill"><strong>${overdue.length}</strong> Overdue</div>`;
 const days=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d});
 const weekday=new Intl.DateTimeFormat('en-ZA',{weekday:'short'});
 $('plannerDays').innerHTML=days.map(d=>{const iso=localISO(d),dayJobs=planned.filter(j=>j.planned_date===iso).sort((a,b)=>a.job_number.localeCompare(b.job_number));return `<div class="planner-day plan-dropzone ${iso===today?'today':''}" data-plan-date="${iso}"><h3>${weekday.format(d)} ${d.getDate()}</h3><div class="planner-day-count">${dayJobs.length} scheduled</div>${dayJobs.map(planCard).join('')||'<div class="planner-empty">Drop a job here or use Schedule</div>'}</div>`}).join('');
 $('plannerBacklog').innerHTML=backlog.sort((a,b)=>a.due_date.localeCompare(b.due_date)).map(planCard).join('')||'<p class="muted">All active jobs are scheduled.</p>';
 $('plannerOverdue').innerHTML=overdue.sort((a,b)=>a.due_date.localeCompare(b.due_date)).map(j=>`<div class="planner-overdue-row"><div><strong>${esc(j.job_number)}</strong> · ${esc(customers.find(c=>c.id===j.customer_id)?.name||'Customer')}<div class="muted">Promised ${esc(j.due_date)} · Scheduled ${esc(j.planned_date||'Not scheduled')}</div></div><button class="secondary" data-schedule="${esc(j.id)}">Schedule</button></div>`).join('')||'<p class="muted">No overdue jobs.</p>';
}
async function setPlannedDate(id,date){
 const j=jobs.find(x=>x.id===id);if(!j)return;
 if(date!==null&&!/^\d{4}-\d{2}-\d{2}$/.test(date)){msg('Choose a valid production date.');return}
 if(j.planned_date===date)return;
 try{check(await db.from('jobs').update({planned_date:date,updated_at:new Date().toISOString()}).eq('id',id));j.planned_date=date;renderPlanner();msg(date?`Scheduled ${j.job_number} for ${date}`:`Moved ${j.job_number} to unscheduled`)}catch(e){msg('Scheduling failed: '+e.message)}
}
$('plannerPrev').onclick=()=>{plannerWeekOffset--;renderPlanner();renderStagePlanner()};
$('plannerNext').onclick=()=>{plannerWeekOffset++;renderPlanner();renderStagePlanner()};
$('plannerToday').onclick=()=>{plannerWeekOffset=0;renderPlanner();renderStagePlanner()};
$('plannerUnscheduled').addEventListener('dragover',e=>{e.preventDefault();e.currentTarget.classList.add('plan-drag-over')});
document.addEventListener('dragstart',e=>{const card=e.target.closest('[data-drag-job]');if(!card)return;e.dataTransfer.setData('text/plain',card.dataset.dragJob);e.dataTransfer.effectAllowed='move'});
document.addEventListener('dragover',e=>{const zone=e.target.closest('[data-plan-date],#plannerUnscheduled');if(!zone)return;e.preventDefault();e.dataTransfer.dropEffect='move';zone.classList.add('plan-drag-over')});
document.addEventListener('dragleave',e=>{const zone=e.target.closest('[data-plan-date],#plannerUnscheduled');if(zone&&!zone.contains(e.relatedTarget))zone.classList.remove('plan-drag-over')});
document.addEventListener('drop',e=>{const zone=e.target.closest('[data-plan-date],#plannerUnscheduled');if(!zone)return;e.preventDefault();zone.classList.remove('plan-drag-over');const id=e.dataTransfer.getData('text/plain');if(id)setPlannedDate(id,zone.id==='plannerUnscheduled'?null:zone.dataset.planDate)});
document.addEventListener('dragend',()=>document.querySelectorAll('.plan-drag-over').forEach(el=>el.classList.remove('plan-drag-over')));
$('scheduleCancel').onclick=()=>$('scheduleModal').classList.add('hide');
$('scheduleForm').onsubmit=async e=>{e.preventDefault();const id=$('scheduleJobId').value;const date=$('scheduleUnscheduled').checked?null:$('scheduleDate').value;if(!date&&!$('scheduleUnscheduled').checked){msg('Select a production date.');return}await setPlannedDate(id,date);$('scheduleModal').classList.add('hide')};
$('scheduleUnscheduled').onchange=e=>{$('scheduleDate').disabled=e.target.checked};
document.addEventListener('click',e=>{const b=e.target.closest('[data-schedule]');if(!b)return;const j=jobs.find(x=>x.id===b.dataset.schedule);if(!j)return;$('scheduleJobId').value=j.id;$('scheduleJobLabel').textContent=`${j.job_number} · Promised ${j.due_date}`;$('scheduleDate').value=j.planned_date||j.due_date;$('scheduleUnscheduled').checked=false;$('scheduleDate').disabled=false;$('scheduleModal').classList.remove('hide')});
// Phase 3.2: date suggestions are based on weekdays, not public holidays or shop capacity.
const stageNames=['Pretreatment','Powder Coating','Curing / QC'];
const stageLabels={'Pretreatment':'Pretreatment','Powder Coating':'Powder Coating','Curing / QC':'Curing / QC'};
function parseDate(iso){const [y,m,d]=iso.split('-').map(Number);return new Date(y,m-1,d,12)}
function previousBusinessDay(iso,count){const d=parseDate(iso);while(count>0){d.setDate(d.getDate()-1);if(d.getDay()!==0&&d.getDay()!==6)count--}return localISO(d)}
function suggestStageDates(due){return [3,2,1].map(n=>previousBusinessDay(due,n))}
function stageFor(j){return stagePlans.filter(p=>p.job_id===j.id)}
function stageCard(p){const j=jobs.find(x=>x.id===p.job_id);if(!j)return '';const c=customers.find(x=>x.id===j.customer_id);return `<article class="stage-card" draggable="true" data-drag-stage="${esc(p.id)}"><strong>${esc(j.job_number)} · ${esc(p.stage)}</strong><small>${esc(c?.name||'Customer')} · Due ${esc(j.due_date)}</small><button class="secondary" data-edit-stage="${esc(p.id)}">Reschedule</button></article>`}
function renderStagePlanner(){
 const active=jobs.filter(j=>j.status!=='Collected');const start=weekStart(plannerWeekOffset);const end=new Date(start);end.setDate(start.getDate()+6);const a=localISO(start),b=localISO(end);
 const stageActive=stagePlans.filter(p=>active.some(j=>j.id===p.job_id));
 $('stageSummary').textContent=`${stageActive.filter(p=>p.planned_date>=a&&p.planned_date<=b).length} stage tasks this week · ${active.filter(j=>!stageActive.some(p=>p.job_id===j.id)).length} jobs without stage dates`;
 $('stageDays').innerHTML=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const iso=localISO(d);const list=stageActive.filter(p=>p.planned_date===iso);return `<div class="planner-day stage-drop" data-stage-day="${iso}"><h3>${esc(new Intl.DateTimeFormat('en-ZA',{weekday:'short',day:'numeric',month:'short'}).format(d))}</h3><div class="planner-day-count">${list.length} tasks</div>${list.map(stageCard).join('')||'<p class="planner-empty">No stages planned</p>'}</div>`}).join('');
 $('stageUnplanned').innerHTML=active.filter(j=>!stageActive.some(p=>p.job_id===j.id)).map(j=>`<div class="stage-unplanned"><strong>${esc(j.job_number)}</strong> · Due ${esc(j.due_date)} <button class="secondary" data-generate-stages="${esc(j.id)}">Suggest stages</button></div>`).join('')||'<p class="muted">All active jobs have a stage schedule.</p>';
}
async function generateStages(j,confirmExisting=false){
 const existing=stageFor(j);
 if(existing.length&&!confirmExisting){msg('This job already has stage dates. Reschedule individual stages instead.');return}
 const dates=suggestStageDates(j.due_date);
 if(dates[0]<localISO(new Date())&&!confirm(`Suggested stages for ${j.job_number} include past dates because the due date is close or overdue. Save suggestions anyway?`))return;
 const rows=stageNames.map((stage,i)=>({job_id:j.id,stage,planned_date:dates[i]}));
 check(await db.from('job_stage_schedule').upsert(rows,{onConflict:'job_id,stage'}));
 await load();msg('Suggested stage dates saved. Review against your actual workload.');
}
async function updateStage(id,date){
 if(!/^\d{4}-\d{2}-\d{2}$/.test(date)){msg('Select a valid date');return}
 try{check(await db.from('job_stage_schedule').update({planned_date:date}).eq('id',id));await load();msg('Production stage rescheduled. Customer due date unchanged.')}catch(e){msg('Stage scheduling failed: '+e.message)}
}
$('stageEditCancel').onclick=()=>$('stageEditModal').classList.add('hide');
$('stageEditForm').onsubmit=async e=>{e.preventDefault();const id=$('stageEditId').value,date=$('stageEditDate').value;await updateStage(id,date);$('stageEditModal').classList.add('hide')};
document.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit-stage]');if(edit){const p=stagePlans.find(x=>x.id===edit.dataset.editStage);if(!p)return;$('stageEditId').value=p.id;$('stageEditDate').value=p.planned_date;$('stageEditLabel').textContent=`${jobs.find(j=>j.id===p.job_id)?.job_number||'Job'} · ${p.stage}`;$('stageEditModal').classList.remove('hide')}const generate=e.target.closest('[data-generate-stages]');if(generate){const j=jobs.find(x=>x.id===generate.dataset.generateStages);if(j)try{await generateStages(j)}catch(err){msg('Could not generate schedule: '+err.message)}}});
document.addEventListener('dragstart',e=>{const card=e.target.closest('[data-drag-stage]');if(card){e.dataTransfer.setData('application/x-endura-stage',card.dataset.dragStage);e.dataTransfer.effectAllowed='move'}});
document.addEventListener('dragover',e=>{if(e.target.closest('[data-stage-day]'))e.preventDefault()});
document.addEventListener('drop',e=>{const zone=e.target.closest('[data-stage-day]');if(!zone)return;const id=e.dataTransfer.getData('application/x-endura-stage');if(id){e.preventDefault();e.stopPropagation();updateStage(id,zone.dataset.stageDay)}});
function renderJobList(){
 const q=($('jobSearch')?.value||'').trim().toLowerCase();
 const visible=jobs.filter(j=>j.status!=='Collected').filter(j=>{const c=customers.find(c=>c.id===j.customer_id);const lines=items.filter(i=>i.job_id===j.id);return [j.job_number,j.status,c?.name,c?.phone,...lines.flatMap(i=>[i.description,i.colour])].join(' ').toLowerCase().includes(q)});
 $('jobs').innerHTML=visible.map(jobHTML).join('')||'<p class="empty">No matching active jobs.</p>';
}
$('jobSearch').addEventListener('input',renderJobList);

function jobHTML(j){const c=customers.find(x=>x.id===j.customer_id)||{};const [cls,urg]=urgency(j);const list=items.filter(i=>i.job_id===j.id);const notification=notices.find(n=>n.job_id===j.id&&n.kind==='collection');return `<div class="job"><div class="job-head"><div><strong>${esc(j.job_number)}</strong> — ${esc(c.name)} <span class="chip ${cls}">${esc(urg)}</span><div class="muted">${esc(c.phone)} · Due ${esc(j.due_date)}</div></div><div><select data-status="${j.id}" aria-label="Change job status">${statuses.map(s=>`<option ${s===j.status?'selected':''}>${esc(s)}</option>`).join('')}</select></div></div><div class="muted">${list.map(i=>`${esc(i.quantity)} × ${esc(i.description)} (${esc(i.colour)})`).join(' · ')||'No items'}</div><div class="job-tools"><button class="secondary" data-edit="${j.id}">✎ Edit job & items</button></div><div class="row"><div><label>Invoice PDF (max 10 MB)</label><input type="file" accept="application/pdf,.pdf" data-file="${j.id}"></div><div>${j.invoice_path?`<button class="secondary" data-invoice="${j.id}">View saved PDF</button>`:'<span class="muted">No invoice uploaded</span>'}</div></div>${notification?`<p class="muted">Collection WhatsApp: ${esc(notification.status.replaceAll('_',' '))}. Manual sending only.</p>`:''}</div>`}
function editItemRow(i={}){const d=document.createElement('div');d.className='edit-item';if(i.id)d.dataset.itemId=i.id;d.innerHTML=`<div class="row"><div><label>Item description</label><input class="e-desc" required value="${esc(i.description||'')}" placeholder="Steel brackets"></div><div><label>Quantity</label><input class="e-qty" type="number" min="1" required value="${Number(i.quantity)||1}"></div><div><label>Colour</label><input class="e-colour" value="${esc(i.colour||'')}" placeholder="Matt black"></div><div><label>Dimensions</label><input class="e-dim" value="${esc(i.dimensions||'')}"></div><div><label>Price (R)</label><input class="e-price" type="number" min="0" step="0.01" value="${Number(i.price)||0}"></div></div><div class="job-tools"><button type="button" class="secondary e-remove">Remove item</button></div>`;d.querySelector('.e-remove').onclick=()=>{if($('editItems').children.length<=1){msg('A job needs at least one item');return}if(d.dataset.itemId)editRemoved.add(d.dataset.itemId);d.remove()};$('editItems').appendChild(d)}
function openEdit(id){const j=jobs.find(x=>x.id===id);if(!j)return;editRemoved=new Set();$('editJobId').value=j.id;$('editJobNo').value=j.job_number;$('editDue').value=j.due_date;$('editNotes').value=j.notes||'';$('editCustomer').value=customers.find(c=>c.id===j.customer_id)?.name||'';$('editItems').innerHTML='';const lines=items.filter(i=>i.job_id===id);if(lines.length)lines.forEach(editItemRow);else editItemRow();$('editModal').classList.remove('hide');$('editJobNo').focus()}
function closeEdit(){$('editModal').classList.add('hide');editRemoved.clear()}
$('closeEdit').onclick=closeEdit;$('cancelEdit').onclick=closeEdit;$('editAddItem').onclick=()=>editItemRow();
$('editModal').addEventListener('click',e=>{if(e.target===$('editModal'))closeEdit()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('editModal').classList.contains('hide'))closeEdit()});
$('editJobForm').onsubmit=async e=>{e.preventDefault();const button=$('saveEdit');button.disabled=true;try{const id=$('editJobId').value;const old=jobs.find(j=>j.id===id);if(!old)throw Error('Job no longer exists. Refresh first.');const rows=[...$('editItems').children].map(el=>({id:el.dataset.itemId||null,description:el.querySelector('.e-desc').value.trim(),quantity:Number(el.querySelector('.e-qty').value),colour:el.querySelector('.e-colour').value.trim(),dimensions:el.querySelector('.e-dim').value.trim(),price:Number(el.querySelector('.e-price').value)||0}));if(!rows.length||rows.some(r=>!r.description||!Number.isInteger(r.quantity)||r.quantity<1||r.price<0))throw Error('Each item needs a description, positive whole-number quantity and valid price.');const nextNumber=$('editJobNo').value.trim();if(!nextNumber)throw Error('Enter a job number.');if(jobs.some(j=>j.id!==id&&j.job_number.toLowerCase()===nextNumber.toLowerCase()))throw Error('That job number already exists.');const due=$('editDue').value;if(!/^\d{4}-\d{2}-\d{2}$/.test(due))throw Error('Choose a valid due date.');const notes=$('editNotes').value;check(await db.from('jobs').update({job_number:nextNumber,due_date:due,notes,updated_at:new Date().toISOString()}).eq('id',id));for(const row of rows){const {id:itemId,...data}=row;if(itemId)check(await db.from('job_items').update(data).eq('id',itemId).eq('job_id',id));else check(await db.from('job_items').insert({...data,job_id:id}))}if(editRemoved.size)check(await db.from('job_items').delete().eq('job_id',id).in('id',[...editRemoved]));closeEdit();await load();msg('Job card and items updated in Supabase.');}catch(err){msg('Save failed: '+err.message+' Refresh and review before retrying.')}finally{button.disabled=false}};
async function transition(id,status){const j=jobs.find(x=>x.id===id);if(!j||j.status===status)return;try{check(await db.from('jobs').update({status,updated_at:new Date().toISOString()}).eq('id',id));check(await db.from('job_history').insert({job_id:id,status}));if(status==='Ready for Collection'){const c=customers.find(x=>x.id===j.customer_id);const text=`Good day ${c?.name||''}, your EnduraCoat job ${j.job_number} is ready for collection.${j.invoice_path?' Please find your invoice attached.':''} Thank you!`;check(await db.from('notifications').upsert({job_id:id,kind:'collection',status:'draft',message:text},{onConflict:'job_id,kind'}));msg('Job ready. Collection message added to Review — NOT sent.')}else msg('Job updated');await load()}catch(e){msg('Could not update job: '+e.message);await load()}}
async function uploadInvoice(id,file){if(!file)return;if(file.type!=='application/pdf'||!file.name.toLowerCase().endsWith('.pdf')||file.size>10*1024*1024){msg('Choose a PDF file under 10 MB.');return}try{const path=`${id}/${crypto.randomUUID()}.pdf`;check(await db.storage.from('invoices').upload(path,file,{contentType:'application/pdf',upsert:false}));check(await db.from('jobs').update({invoice_path:path,invoice_name:file.name}).eq('id',id));msg('Invoice uploaded securely');await load()}catch(e){msg('Upload failed: '+e.message)}}
async function viewInvoice(id){const j=jobs.find(x=>x.id===id);if(!j?.invoice_path)return;try{const r=check(await db.storage.from('invoices').createSignedUrl(j.invoice_path,60));window.open(r.signedUrl,'_blank','noopener,noreferrer')}catch(e){msg(e.message)}}
async function makeDelayReviews(){for(const j of jobs){if(urgency(j)[0]!=='overdue'||['Collected','Ready for Collection'].includes(j.status)||notices.some(n=>n.job_id===j.id&&n.kind==='delay'))continue;const c=customers.find(x=>x.id===j.customer_id);const message=`Good day ${c?.name||''}, we apologise that your EnduraCoat job ${j.job_number} has been delayed. We will confirm an updated collection date shortly.`;check(await db.from('notifications').insert({job_id:j.id,kind:'delay',status:'draft',message}));}await load()}
async function boot(){if(!configured){$('setup').classList.remove('hide');return}db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);const {data:{session}}=await db.auth.getSession();await authView(session);db.auth.onAuthStateChange((_event,session)=>{setTimeout(()=>authView(session),0)})}
async function authView(session){$('login').classList.toggle('hide',!!session);$('app').classList.toggle('hide',!session);$('logout').classList.toggle('hide',!session);if(session){try{const staff=check(await db.from('staff').select('user_id').eq('user_id',session.user.id).maybeSingle());if(!staff){$('app').classList.add('hide');msg('Account not authorised. Add this user UUID to public.staff in Supabase.');return}await load();await makeDelayReviews();await migratePendingReviews()}catch(e){msg('Database error: '+e.message)}}}
$('loginForm').onsubmit=async e=>{e.preventDefault();const r=await db.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(r.error)msg(r.error.message)};
$('logout').onclick=()=>db.auth.signOut();document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>show(b.dataset.tab));$('refresh').onclick=()=>load().catch(e=>msg(e.message));$('addItem').onclick=itemRow;itemRow();
$('jobForm').onsubmit=async e=>{e.preventDefault();const b=$('saveJob');b.disabled=true;try{const enteredNumber=$('jobno').value.trim();if(jobs.some(j=>j.job_number.toLowerCase()===enteredNumber.toLowerCase())){const input=$('jobno');input.focus();throw Error(`Job number ${enteredNumber} already exists. Please enter a different job number.`)}let c=customers.find(c=>c.name.toLowerCase()===$('customer').value.trim().toLowerCase()&&c.phone===$('phone').value.trim());if(!c)c=check(await db.from('customers').insert({name:$('customer').value.trim(),phone:$('phone').value.trim()}).select().single());const job=check(await db.from('jobs').insert({job_number:$('jobno').value.trim(),customer_id:c.id,due_date:$('due').value,notes:$('notes').value}).select().single());const rows=[...document.querySelectorAll('#items .item')].map(x=>({job_id:job.id,description:x.querySelector('.desc').value,quantity:Number(x.querySelector('.qty').value),colour:x.querySelector('.colour').value,dimensions:x.querySelector('.dimensions').value,price:Number(x.querySelector('.price').value)||0}));check(await db.from('job_items').insert(rows));check(await db.from('job_history').insert({job_id:job.id,status:'New'}));
 let stageWarning='';try{const dates=suggestStageDates(job.due_date);check(await db.from('job_stage_schedule').upsert(stageNames.map((stage,i)=>({job_id:job.id,stage,planned_date:dates[i]})),{onConflict:'job_id,stage'}))}catch(err){stageWarning=' Job created, but automatic stage scheduling failed: '+err.message}
 $('jobForm').reset();$('items').innerHTML='';itemRow();await load();show('dashboard');msg('Job saved to cloud.'+stageWarning)}catch(e){if(e.code==='23505'){const duplicateJob=/job_number|jobs_job_number/i.test(String(e.message||'')+' '+String(e.details||''));if(duplicateJob){$('jobno').focus();msg('This job number is already in use. Choose a different job number and try again.')}else msg('A record with these details already exists. '+(e.message||''));}else msg('Save failed: '+e.message)}finally{b.disabled=false}};
document.addEventListener('change',async e=>{const t=e.target;if(t.dataset.status)await transition(t.dataset.status,t.value);if(t.dataset.file)await uploadInvoice(t.dataset.file,t.files?.[0])});async function migratePendingReviews(){const pending=notices.filter(n=>n.status==='pending_integration');if(!pending.length)return;for(const n of pending)check(await db.from('notifications').update({status:'draft'}).eq('id',n.id));await load()}
async function saveReviewMessage(id){const field=[...document.querySelectorAll('[data-message]')].find(x=>x.dataset.message===id);const n=notices.find(x=>x.id===id);if(!field||!n)return null;const message=field.value.trim();if(!message){msg('Message cannot be empty');return null}if(message!==n.message){check(await db.from('notifications').update({message}).eq('id',id));n.message=message}return message}
document.addEventListener('click',async e=>{const t=e.target.closest('button');if(!t)return;try{if(t.dataset.edit)openEdit(t.dataset.edit);if(t.dataset.invoice||t.dataset.reviewInvoice)await viewInvoice(t.dataset.invoice||t.dataset.reviewInvoice);if(t.dataset.copy){const message=await saveReviewMessage(t.dataset.copy);if(message){await navigator.clipboard.writeText(message);msg('Message copied')}}if(t.dataset.whatsapp){const id=t.dataset.whatsapp,message=await saveReviewMessage(id);if(!message)return;const n=notices.find(x=>x.id===id),j=jobs.find(x=>x.id===n.job_id),c=customers.find(x=>x.id===j?.customer_id),phone=whatsappPhone(c?.phone);if(!phone){msg('Customer needs a valid WhatsApp number');return}window.open(`https://wa.me/${phone}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');msg('WhatsApp opened. Check recipient and send manually; attach PDF if needed.')}if(t.dataset.sent){const id=t.dataset.sent;if(!confirm('Have you actually sent this message in WhatsApp?'))return;if(!await saveReviewMessage(id))return;check(await db.from('notifications').update({status:'sent'}).eq('id',id));msg('Marked as sent (manual confirmation)');await load()}if(t.dataset.dismiss){check(await db.from('notifications').update({status:'failed'}).eq('id',t.dataset.dismiss));msg('Message dismissed');await load()}}catch(err){msg('Review action failed: '+err.message)}});
boot().catch(e=>msg(e.message));
